all:
	# python make_csv.py
	python -c 'import gpkit.tools; exec gpkit.tools.mdmake("gasmale.md")'
	pandoc --template default.latex gasmale.md.tex.md -o "/Users/mjburton11/Dropbox (MIT)/16.82GasMALE/Management/GPKitReports/gasmale.pdf"
